apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-deployment
  labels:
    app: clipclassifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clipclassifier
  template:
    metadata:
      labels:
        app: clipclassifier
    spec:
      containers:
      - name: clipclassifier
        image: clip_classifier_k8:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: clip-service
spec:
  selector:
    app: clipclassifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clip-ingress
  labels:
    name: myingress
spec:
  rules:
    - host: clip.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: clip-service
                port: 
                  number: 80



