
FROM python:3.9.5-slim-buster

RUN pip3 install torch torchvision  --no-cache-dir --index-url https://download.pytorch.org/whl/cpu

RUN pip3 install fastapi[all] tiktoken  --no-cache-dir

WORKDIR /workspace


# COPY ../../configs /workspace/configs
COPY ../../models/hp_gpt_scripted.pt /workspace/models/hp_gpt_scripted.pt
COPY ../../deployment/gpt_fastapi.py /workspace/deployment/gpt_fastapi.py

CMD ["uvicorn", "deployment.gpt_fastapi:app", "--host", "0.0.0.0", "--port", "80"]

EXPOSE 80/tcp

#aws

# FROM python:3.11-slim-buster

# RUN pip3 install torch torchvision  --no-cache-dir --index-url https://download.pytorch.org/whl/cpu

# RUN pip3 install gradio tiktoken boto3 --no-cache-dir

# WORKDIR /workspace


# COPY ./gpt_demo.py /workspace/

# CMD ["python3","gpt_demo.py"]

# EXPOSE 80/tcp

