version: '3.9'
services:
  train:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    container_name: dlpkg
    volumes:
      - ../logs:/workspace/logs

    #command: dl_pkg_train experiment=mnist
    command: dl_pkg_train -m hydra/launcher=joblib hydra.launcher.n_jobs=5 experiment=cifar_vit model.net.patch_size=1,2,4,8,16 data.num_workers=0

  ml_flow:
    build:
      context: ./
      dockerfile: Dockerfile.experiment
    container_name: mlflow
    volumes:
      - ../logs/mlflow:/workspace/
    expose:
      - 5000
    ports:
      - 5001:5000
    command: mlflow ui -h 0.0.0.0
    # ports:
    #   - 5001:5000
    #   - 43801:43800
    #   - 6007:6006
    # command: starter_script.sh

  aim:
    build:
      context: ./
      dockerfile: Dockerfile.experiment
    container_name: aim
    volumes:
      - ../logs/.aim:/workspace/.aim
    expose:
      - 43800
    ports:
      - 43801:43800
    command: aim up -h 0.0.0.0

  tensorboard:
    build:
      context: ./
      dockerfile: Dockerfile.experiment
    container_name: tensorboard
    volumes:
      - ../logs/tensorboard/:/workspace/
    expose:
      - 6006
    ports:
      - 6007:6006
    command: tensorboard --logdir . --host 0.0.0.0

  
  demo:
    build:
      context: ../  #to ensure it has access to all files under dl-package for copying anything in Dockerfile.demo
      dockerfile: .devcontainer/Dockerfile.demo
    container_name: demo
    expose:
      - 8080
    ports:
      - 8080:8080
    command: python3 dl_pkg/demo.py
