# apiVersion: v1
# kind: Service
# metadata:
#   name: model-server-service
# spec:
#   selector:
#     app: model-server
#   ports:
#   - port: 9000
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
    name: "{{ .Values.appName.model }}-service"
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: "{{ .Values.appName.model }}"
    ports:
        - port: 9000
          targetPort: 80