# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: model-server
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: model-server
#   template:
#     metadata:
#       labels:
#         app: model-server
#     spec:
#       containers:
#       - name: model-server
#         image: model_server:latest
#         imagePullPolicy: Never
#         resources:
#           limits:
#             memory: "600Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80
#         env:
#           - name: REDIS_HOST
#             valueFrom:
#               configMapKeyRef:
#                 name:  redis-config
#                 key: hostname
#           - name: REDIS_PORT
#             valueFrom:
#               configMapKeyRef:
#                 name:  redis-config
#                 key: port
#           - name: REDIS_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: redis-secret
#                 key: db_password
#           - name: TIMM_MODEL
#             valueFrom:
#                 configMapKeyRef:
#                   name:  model-server-config
#                   key: timm_model


apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.model }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appName.model }}
    template:
        metadata:
            labels:
                app: {{ .Values.appName.model }}
        spec:
            containers:
                - name: {{ .Values.appName.model }}
                  image: {{ .Values.image.modelServer }}
                  imagePullPolicy: Never
                  ports:
                      - containerPort: {{.Values.appName.modelport}}
                  env:
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: hostname
                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: port
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretKey.redis }}
                                key: db_password
                      - name: "TIMM_MODEL"
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.modelServer }}
                                key: timm_model