# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: web-server
#   labels:
#     app: web-server
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: web-server
#   template:
#     metadata:
#       labels:
#         app: web-server
#     spec:
#       containers:
#       - name: web-server
#         image: web_server:latest
#         imagePullPolicy: Never
#         resources:
#           limits:
#             memory: "200Mi"
#             cpu: "500m"
#         ports:
#           - containerPort: 80
#         env:
#           - name: REDIS_HOST
#             valueFrom:
#               configMapKeyRef:
#                 name:  redis-config
#                 key: hostname
#           - name: REDIS_PORT
#             valueFrom:
#               configMapKeyRef:
#                 name:  redis-config
#                 key: port
#           - name: REDIS_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: redis-secret
#                 key: db_password
#           - name: MODEL_SERVER_URL
#             valueFrom:
#               configMapKeyRef:
#                 name:  model-server-config
#                 key: model_server_url


apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.web }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.appName.web }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appName.web }}
    template:
        metadata:
            labels:
                app: {{ .Values.appName.web }}
        spec:
            containers:
                - name: {{ .Values.appName.web }}
                  image: {{ .Values.image.webServer }}
                  imagePullPolicy: Never
                  # resources:
                  #     limits:
                  #         memory: "200Mi"
                  #         cpu: "500m"
                  ports:
                      - containerPort: {{.Values.appName.webport}}
                  env:
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: hostname
                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.redis }}
                                key: port
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretKey.redis }}
                                key: db_password
                      - name: MODEL_SERVER_URL
                        valueFrom:
                            configMapKeyRef:
                                name: {{ .Values.configMap.modelServer }}
                                key: model_server_url