#secrets are base64 encoded
#get base64 using echo -n "reallydifficultpassword" | base64
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  db_password: cmVhbGx5ZGlmZmljdWx0cGFzc3dvcmQ=