apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-store
  # labels:
  #   type: "amazonEBS"
spec:
  accessModes:
      - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store-claim
  # labels:
  #   type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeName: model-store
  resources:
    requests:
      storage: 1Gi